config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  scope :plan, -> { where(status: 'plan').order(:created_at).reverse_order }
  scope :done, -> { where(status: 'done').order(:created_at).reverse_order }

  def plan?
    status.to_s == 'plan'
  end

  def done?
    status.to_s == 'done'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.plan + Task.done
    @new_task = Task.new
  end

  def create
    Task.create!(create_params)
    redirect_to action: 'index'
  end

  private
  def create_params
    params.require(:task).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTodo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/tasks/_task.slim
li.list-group-item class="#{'list-group-item-success' if task.done?}"
  label
    input type="checkbox" data-post-url="#{task_path(task.id)}" value="#{task.done?}" class="task-checkbox"
    h4.list-group-item-heading style="display: inline" = task.name
    p.list-group-item-text = task.description

app/views/tasks/index.html.slim
h1 Todo

div.row
  div.col-sm-offset-3.col-sm-6
    div.row
      div.col-sm-12
        ul.list-group
          = render @tasks

    = form_for :task, url: tasks_path do |f|
      legend タスクの追加
      div.row
        div.col-sm-10
          = f.text_field :name, class: 'form-control', placeholder: 'タスク名'
        div.col-sm-2
          = f.submit '作成', class: 'btn btn-primary'
      div.row
        div.col-sm-12
          = f.text_area :description, class: 'form-control', placeholder: '説明'

javascript:
  $(document).ready(function () {
    $('.task-checkbox').change(function () {
      var self = $(this);
      var url = self.data('post-url'), status = self.is(':checked') ? 'done' : 'plan';
      $.post('#{task_path(}')
    });
  });